services:
  origin:
    image: nginx:alpine
    container_name: mini_origin
    ports:
      - "8081:80"
    volumes:
      - ./content:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/index.html | grep -q 'OK origin'"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  edge:
    image: nginx:alpine
    container_name: mini_edge
    depends_on:
      - origin
    ports:
      - "8080:80"
    volumes:
      - ./edge/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./edge/cache:/var/cache/nginx
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health | grep -q OK"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s

  exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    container_name: mini_exporter
    depends_on:
      - edge
    command: ["-nginx.scrape-uri=http://edge/stub_status"]
    ports:
      - "9113:9113"

  drm:
    image: python:3.11-slim
    container_name: mini_drm
    working_dir: /app
    environment:
      - DRM_SECRET=change-me
    volumes:
      - ./drm:/app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && python app.py"
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus:latest
    container_name: mini_prometheus
    depends_on:
      - exporter
      - drm
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  alertmanager:
    image: prom/alertmanager:latest
    container_name: mini_alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: mini_grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
