apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: drm-claim0
  name: drm-claim0
  namespace: edge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
