apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: edge-claim0
  name: edge-claim0
  namespace: edge
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
