apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: edge-claim1
  name: edge-claim1
  namespace: edge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
