apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /mnt/f/Software Developer/Porfolio/Telecentro_Labs/min-lab-ott/mini-lab-ott/mini-lab-ott/docker-compose.yml -o /mnt/f/Software Developer/Porfolio/Telecentro_Labs/min-lab-ott/mini-lab-ott/mini-lab-ott/k8s --namespace edge --volumes emptyDir
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: grafana
  name: grafana
  namespace: edge
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: grafana
