apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /mnt/f/Software Developer/Porfolio/Telecentro_Labs/min-lab-ott/mini-lab-ott/mini-lab-ott/docker-compose.yml -o /mnt/f/Software Developer/Porfolio/Telecentro_Labs/min-lab-ott/mini-lab-ott/mini-lab-ott/k8s --namespace edge --volumes emptyDir
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: prometheus
  name: prometheus
  namespace: edge
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: prometheus
