apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/ --namespace edge
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
  namespace: monitoring
spec:
  ports:
    - name: "9093"
      port: 9093
      targetPort: 9093
  selector:
    io.kompose.service: alertmanager
