apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: alertmanager-claim0
  name: alertmanager-claim0
  namespace: monitoring
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
