apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/ --namespace edge
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alertmanager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/ --namespace edge
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/mini-lab-ott-default: "true"
        io.kompose.service: alertmanager
    spec:
      containers:
        - image: prom/alertmanager:latest
          name: mini-alertmanager
          ports:
            - containerPort: 9093
              hostPort: 9093
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/alertmanager/alertmanager.yml
              name: alertmanager-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: alertmanager-claim0
          persistentVolumeClaim:
            claimName: alertmanager-claim0
            readOnly: true
