apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: grafana-claim2
  name: grafana-claim2
  namespace: monitoring
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
